### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by ctsimpouris** [lyhmyd1211/react-Back-To-Top#1]
It seems that it's not SSR friendly

```
WebpackError: ReferenceError: window is not defined  
BackToTop.js:44 new BackToTop
[lib]/[react-back-to-top]/dist/BackToTop.js:44:1
```

Any idea how to overcome?

**Comment by lyhmyd1211** [comment]
I did not consider SSR support when I created this component. Now you can get SSR support by updating to the latest version.
